language: node_js
node_js: 
  - 12

script:
  - "yarn lint"
  - "yarn test"

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: "yarn semantic-release"
